POST http://localhost:3000/movements
Content-Type: application/json

{
"type": "Mercado",
"value": 4
}

###

GET http://localhost:3000/db

###

GET http://localhost:3000/transaction_types

###

GET http://localhost:3000/get_expense

###

POST http://localhost:3000/post_categories"

